import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { morKhor } from "@/shared/assets/fonts";
import { ReduxProvider } from "@/shared/providers";
import dynamic from "next/dynamic";

const Navbar = dynamic(() => import("../shared/components/navbar.component"));

const Footer = dynamic(() => import("../shared/components/footer.component"));

// const Navbar = dynamic(
//   () => import("../shared/components/navbar.component")
// )

interface RootLayoutProps {
  children: React.ReactNode;
  params: {
    locale: string;
  };
}

export function generateStaticParams() {
  return;
}

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "CoE Schedule",
  description: "Generated by MITAPRAB",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        // className={`${geistSans.variable} ${geistMono.variable} ${morKhor.variable}`}
        className={`${morKhor.variable}`}
      >
        <ReduxProvider>
          <Navbar locale="th" />
          {children}
        </ReduxProvider>
          <Footer/>
      </body>
    </html>
  );
}
